theme = "grv"

[editor]
auto-pairs = false
idle-timeout = 50
gutters = ["diagnostics"]

[editor.lsp]
# display progress messages in status-line
display-messages = true

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
tab = "â"

[keys.normal]
"=" = ":pipe fmt -w 80"
